# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20161007_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
