# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20161007_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpTable',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
