# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20161012_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWithPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TmpTable',
        ),
        migrations.AlterField(
            model_name='good',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Cpu', verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Имя'),
        ),
    ]
