# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20161012_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductWithPrice',
        ),
    ]
