# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_product_productwithprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwithprice',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductWithPrice',
        ),
    ]
