# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20161012_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductWithPrice',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('goods.product',),
        ),
    ]
