# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_product_productwithprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductWithPrice',
        ),
        migrations.AddField(
            model_name='cpu',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
