# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20161019_1612'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cpu',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
